services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./.services/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: test
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRES_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: test
      WORDPRESS_DEBUG: 1
    volumes:
      - ./.services/wordpress/:/var/www/html
      - ./theme/:/var/www/html/wp-content/themes/test
      - ./plugin/:/var/www/html/wp-content/plugins/test_plugin
      - ./.services/custom.ini:/usr/local/etc/php/conf.d/custom.ini
